services:
  app:
    build: .
    container_name: mt5sdk_container
    restart: always
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis
    command: sh -c "pnpm start"
  redis:
    image: redis:latest
    container_name: redisBullMQ_container
    ports:
      - '${BULLMQ_REDIS_PORT}:6379'
      - '127.0.0.1:${BULLMQ_REDIS_PORT}:${BULLMQ_REDIS_PORT}'
    volumes:
      - redis_data:/data
    command: redis-server --port ${BULLMQ_REDIS_PORT} --requirepass ${BULLMQ_REDIS_PASSWORD}
    restart: always

volumes:
  redis_data:
