version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redisBullMQ
    ports:
      - "${BULLMQ_REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${BULLMQ_REDIS_PASSWORD}
    restart: always

volumes:
  redis_data:
